### PR TITLE
chore: bump version

### PR DESCRIPTION
**Pull request by elbkind**
Upgrade dependencies due to security vulnerabilities

### CODE REVIEW

**Comment by KnisterPeter** [comment]
@elbkind Please remove the confict, then I can merge this change.

**Comment by elbkind** [comment]
done.
Would you mind updating the lib on npm?

**Comment by KnisterPeter** [comment]
@elbkind Published as 1.1.0

**Comment by elbkind** [comment]
> @elbkind Published as 1.1.0

Danke

**Pull request merged**
